#!/bin/bash
rm -f client.jks server-chain.jks
cp `find /Library/Java/JavaVirtualMachines /etc -name cacerts -type f -print 2>/dev/null | head -1` server-chain.jks ; chmod +w server-chain.jks
echo "Adding intermediate certificate to server-chain.jks"
keytool -import -file intermediate.pem -alias intermediate -trustcacerts -keystore server-chain.jks -storepass changeit -noprompt
retval=$?
if [ $retval -ne 0 ]; then
    echo "Return code was not zero but $retval"
    exit 1
fi
echo "Adding root certificate to server-chain.jks"
keytool -import -file ca.pem -alias root -trustcacerts -keystore server-chain.jks -storepass changeit -noprompt
retval=$?
if [ $retval -ne 0 ]; then
    echo "Return code was not zero but $retval"
    exit 1
fi
# echo "Adding mq_server certificate to server-chain.jks"
# keytool -import -file mq_server.pem -alias mq_server -trustcacerts -keystore server-chain.jks -storepass changeit -noprompt
openssl pkcs12 -export -in client.pem -inkey client.key -certfile client.pem -out clientKeyStore.p12 -passout pass:changeit
retval=$?
if [ $retval -ne 0 ]; then
    echo "Return code was not zero but $retval"
    exit 1
fi
echo "Adding user's private key to client.jks"
keytool -importkeystore -srckeystore clientKeyStore.p12 -srcstoretype pkcs12 -destkeystore client.jks -deststoretype JKS -noprompt -storepass changeit -srcstorepass changeit
retval=$?
if [ $retval -ne 0 ]; then
    echo "Return code was not zero but $retval"
    exit 1
fi
keytool -changealias -keystore client.jks -alias 1 -destalias client -storepass changeit
retval=$?
if [ $retval -ne 0 ]; then
    echo "Return code was not zero but $retval"
    exit 1
fi
mv *jks src/main/resources
rm -f *pem *crt *key *p12

echo "JKS files all prepared correctly"