#!/bin/bash

LIST="CAMEL_VALUES"
# Before we get started, just check we have all the vars we need
for var in $LIST; do
	if [ "${!var}" == "" ] ; then
		echo "$var not set"
		exit 1
	fi
done
# Backup out properties file
if [ -z /tmp/broker.properties ] ; then
	cp -n src/main/resources/broker.properties /tmp/broker.properties
fi
chmod +x jks_generate
cd node
npm i
node parse_params.js prepare
cd ..
./jks_generate
