FROM ibm_java
MAINTAINER Giles Gamon "giles@lsiarchi.consulting"

ADD safe /tmp/safe
RUN git clone https://github.com/gilesgamon/ssl-wmq-camel-sqs-broker.git
RUN cd ssl-wmq-camel-sqs-broker && source /tmp/safe/secrets && ./parse_params && mvn clean install && cp target/*jar /tmp && cp server-chain.jks /tmp
RUN rm -rf /tmp/safe